version: '3'

services:

  nginx:
    build: './nginx'
    restart: 'on-failure'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './certs:/root/.local/share/mkcert'
      - './web:/var/www/html'
    depends_on:
      - 'php-fpm'

  php-fpm:
    build: '../7.3'
    restart: 'on-failure'
    environment:
      REMOTE_DEBUG: '0'
    volumes:
      - './web:/var/www/html'
